export const photoList = [
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },
  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: 1,
    second_user: 4,
    third_user: 3,
  },

  {
    alt: "프로필 사진",
    title: "개꿀잼파티",
    board_image_url: "../profile/profileimg.png",
    content: "오늘은 내가 일등이다!!",
    create_dtm: "2023-02-25T16:10:45.8306309",
    first_user: null,
    second_user: null,
    third_user: null,
  },
];
